name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      invironment: dev
      aws-assume-role-arn: "arn:aws:iam::102282314095:role/github-actions-marianapiccolo-pipeline"
      aws-region: "eu-west-3"
      aws-statefile-s3-bucket: "marianapiccolo-eu-west-3-terraform-statefile"
      aws-lock-dynamodb-table: "marianapiccolo-eu-west-3-terraform-lock"
